var classes = [
    {
        "name": "admin\\Main",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "render",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "templates\\header",
            "templates\\footer"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 14,
        "vocabulary": 6,
        "volume": 36.19,
        "difficulty": 1,
        "effort": 36.19,
        "level": 1,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 36.19,
        "number_operators": 4,
        "number_operands": 10,
        "number_operators_unique": 1,
        "number_operands_unique": 5,
        "cloc": 0,
        "loc": 96,
        "lloc": 91,
        "mi": 46.22,
        "mIwoC": 46.22,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 4,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 4,
        "package": "admin\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Auth\\AuthClass",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "AuthF",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 4,
        "vocabulary": 4,
        "volume": 8,
        "difficulty": 0.5,
        "effort": 4,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 16,
        "number_operators": 1,
        "number_operands": 3,
        "number_operators_unique": 1,
        "number_operands_unique": 3,
        "cloc": 2,
        "loc": 18,
        "lloc": 16,
        "mi": 91.83,
        "mIwoC": 67.14,
        "commentWeight": 24.69,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "Auth\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "bodeguero\\Main",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "render",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "templates\\header2",
            "LoginUser\\Database"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 104,
        "vocabulary": 45,
        "volume": 571.15,
        "difficulty": 3.76,
        "effort": 2145.31,
        "level": 0.27,
        "bugs": 0.19,
        "time": 119,
        "intelligentContent": 152.06,
        "number_operators": 27,
        "number_operands": 77,
        "number_operators_unique": 4,
        "number_operands_unique": 41,
        "cloc": 0,
        "loc": 128,
        "lloc": 123,
        "mi": 34.7,
        "mIwoC": 34.7,
        "commentWeight": 0,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 9,
        "totalStructuralComplexity": 9,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 9,
        "package": "bodeguero\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "LoginUser\\Database",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getConnection",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 17,
        "vocabulary": 12,
        "volume": 60.94,
        "difficulty": 3,
        "effort": 182.83,
        "level": 0.33,
        "bugs": 0.02,
        "time": 10,
        "intelligentContent": 20.31,
        "number_operators": 5,
        "number_operands": 12,
        "number_operators_unique": 4,
        "number_operands_unique": 8,
        "cloc": 0,
        "loc": 17,
        "lloc": 17,
        "mi": 60.39,
        "mIwoC": 60.39,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 2,
        "package": "LoginUser\\",
        "pageRank": 0.46,
        "afferentCoupling": 21,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "CRUD\\DeletePedidoClass",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "DeletePedidoF",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "LoginUser\\Database"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 32,
        "vocabulary": 16,
        "volume": 128,
        "difficulty": 1.79,
        "effort": 228.57,
        "level": 0.56,
        "bugs": 0.04,
        "time": 13,
        "intelligentContent": 71.68,
        "number_operators": 7,
        "number_operands": 25,
        "number_operators_unique": 2,
        "number_operands_unique": 14,
        "cloc": 0,
        "loc": 30,
        "lloc": 29,
        "mi": 52.94,
        "mIwoC": 52.94,
        "commentWeight": 0,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 1,
        "package": "CRUD\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "CRUD\\DeleteProviderClass",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "DeleteProviderF",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "LoginUser\\Database"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 32,
        "vocabulary": 16,
        "volume": 128,
        "difficulty": 1.79,
        "effort": 228.57,
        "level": 0.56,
        "bugs": 0.04,
        "time": 13,
        "intelligentContent": 71.68,
        "number_operators": 7,
        "number_operands": 25,
        "number_operators_unique": 2,
        "number_operands_unique": 14,
        "cloc": 0,
        "loc": 31,
        "lloc": 29,
        "mi": 52.94,
        "mIwoC": 52.94,
        "commentWeight": 0,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 1,
        "package": "CRUD\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "CRUD\\DeleteUserClass",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "DeleteUserF",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "LoginUser\\Database"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 32,
        "vocabulary": 16,
        "volume": 128,
        "difficulty": 1.79,
        "effort": 228.57,
        "level": 0.56,
        "bugs": 0.04,
        "time": 13,
        "intelligentContent": 71.68,
        "number_operators": 7,
        "number_operands": 25,
        "number_operators_unique": 2,
        "number_operands_unique": 14,
        "cloc": 0,
        "loc": 30,
        "lloc": 29,
        "mi": 52.94,
        "mIwoC": 52.94,
        "commentWeight": 0,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 1,
        "package": "CRUD\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "CRUD\\EditMaterialClass",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "EditMaterialF",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "LoginUser\\Database"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 41,
        "vocabulary": 21,
        "volume": 180.09,
        "difficulty": 1.79,
        "effort": 322.26,
        "level": 0.56,
        "bugs": 0.06,
        "time": 18,
        "intelligentContent": 100.64,
        "number_operators": 7,
        "number_operands": 34,
        "number_operators_unique": 2,
        "number_operands_unique": 19,
        "cloc": 0,
        "loc": 74,
        "lloc": 59,
        "mi": 45.31,
        "mIwoC": 45.31,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 36,
        "totalStructuralComplexity": 36,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 36,
        "package": "CRUD\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "CRUD\\EditProviderClass",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "EditProviderF",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "LoginUser\\Database"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 40,
        "vocabulary": 20,
        "volume": 172.88,
        "difficulty": 1.83,
        "effort": 316.94,
        "level": 0.55,
        "bugs": 0.06,
        "time": 18,
        "intelligentContent": 94.3,
        "number_operators": 7,
        "number_operands": 33,
        "number_operators_unique": 2,
        "number_operands_unique": 18,
        "cloc": 1,
        "loc": 69,
        "lloc": 58,
        "mi": 54.87,
        "mIwoC": 45.59,
        "commentWeight": 9.27,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 36,
        "totalStructuralComplexity": 36,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 36,
        "package": "CRUD\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "CRUD\\EditPedidoClass",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "EditPedidoF",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "LoginUser\\Database"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 36,
        "vocabulary": 17,
        "volume": 147.15,
        "difficulty": 1.93,
        "effort": 284.49,
        "level": 0.52,
        "bugs": 0.05,
        "time": 16,
        "intelligentContent": 76.11,
        "number_operators": 7,
        "number_operands": 29,
        "number_operators_unique": 2,
        "number_operands_unique": 15,
        "cloc": 1,
        "loc": 97,
        "lloc": 77,
        "mi": 51.23,
        "mIwoC": 43.4,
        "commentWeight": 7.83,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 36,
        "totalStructuralComplexity": 36,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 36,
        "package": "CRUD\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "CRUD\\EditUserClass",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "EditUserF",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "LoginUser\\Database"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 68,
        "vocabulary": 30,
        "volume": 333.67,
        "difficulty": 3.06,
        "effort": 1019.54,
        "level": 0.33,
        "bugs": 0.11,
        "time": 57,
        "intelligentContent": 109.2,
        "number_operators": 13,
        "number_operands": 55,
        "number_operators_unique": 3,
        "number_operands_unique": 27,
        "cloc": 1,
        "loc": 153,
        "lloc": 142,
        "mi": 41.36,
        "mIwoC": 35.11,
        "commentWeight": 6.25,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 36,
        "totalStructuralComplexity": 36,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 36,
        "package": "CRUD\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "CRUD\\DeleteMaterialClass",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "DeleteMaterialF",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "LoginUser\\Database"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 31,
        "vocabulary": 16,
        "volume": 124,
        "difficulty": 1.71,
        "effort": 212.57,
        "level": 0.58,
        "bugs": 0.04,
        "time": 12,
        "intelligentContent": 72.33,
        "number_operators": 7,
        "number_operands": 24,
        "number_operators_unique": 2,
        "number_operands_unique": 14,
        "cloc": 1,
        "loc": 32,
        "lloc": 28,
        "mi": 66.89,
        "mIwoC": 53.37,
        "commentWeight": 13.52,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 1,
        "package": "CRUD\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "CRUD\\UpdateMaterialClass",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "UpdateMaterialF",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "LoginUser\\Database"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 47,
        "vocabulary": 16,
        "volume": 188,
        "difficulty": 1.23,
        "effort": 231.87,
        "level": 0.81,
        "bugs": 0.06,
        "time": 13,
        "intelligentContent": 152.43,
        "number_operators": 10,
        "number_operands": 37,
        "number_operators_unique": 1,
        "number_operands_unique": 15,
        "cloc": 0,
        "loc": 27,
        "lloc": 24,
        "mi": 53.83,
        "mIwoC": 53.83,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 16,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 16,
        "package": "CRUD\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "CRUD\\UpdatePedidoClass",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "UpdatePedidoF",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "LoginUser\\Database"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 42,
        "vocabulary": 15,
        "volume": 164.09,
        "difficulty": 1.18,
        "effort": 193.39,
        "level": 0.85,
        "bugs": 0.05,
        "time": 11,
        "intelligentContent": 139.23,
        "number_operators": 9,
        "number_operands": 33,
        "number_operators_unique": 1,
        "number_operands_unique": 14,
        "cloc": 0,
        "loc": 26,
        "lloc": 23,
        "mi": 54.65,
        "mIwoC": 54.65,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 16,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 16,
        "package": "CRUD\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "CRUD\\UpdateProviderClass",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "UpdateProviderF",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "LoginUser\\Database"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 48,
        "vocabulary": 16,
        "volume": 192,
        "difficulty": 1.27,
        "effort": 243.2,
        "level": 0.79,
        "bugs": 0.06,
        "time": 14,
        "intelligentContent": 151.58,
        "number_operators": 10,
        "number_operands": 38,
        "number_operators_unique": 1,
        "number_operands_unique": 15,
        "cloc": 1,
        "loc": 29,
        "lloc": 24,
        "mi": 67.96,
        "mIwoC": 53.77,
        "commentWeight": 14.19,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 16,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 16,
        "package": "CRUD\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "CRUD\\updateUserClass",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "updateUserF",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "LoginUser\\Database"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 57,
        "vocabulary": 18,
        "volume": 237.69,
        "difficulty": 1.32,
        "effort": 314.58,
        "level": 0.76,
        "bugs": 0.08,
        "time": 17,
        "intelligentContent": 179.58,
        "number_operators": 12,
        "number_operands": 45,
        "number_operators_unique": 1,
        "number_operands_unique": 17,
        "cloc": 0,
        "loc": 29,
        "lloc": 26,
        "mi": 52.36,
        "mIwoC": 52.36,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 16,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 16,
        "package": "CRUD\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "gerente\\Main",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "render",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 4,
        "vocabulary": 4,
        "volume": 8,
        "difficulty": 0.5,
        "effort": 4,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 16,
        "number_operators": 1,
        "number_operands": 3,
        "number_operators_unique": 1,
        "number_operands_unique": 3,
        "cloc": 0,
        "loc": 32,
        "lloc": 27,
        "mi": 62.32,
        "mIwoC": 62.32,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "gerente\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "historial\\Main",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "render",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 5,
        "ccnMethodMax": 5,
        "externals": [
            "templates\\header",
            "LoginUser\\Database",
            "templates\\Footer"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 113,
        "vocabulary": 42,
        "volume": 609.33,
        "difficulty": 5.27,
        "effort": 3211.34,
        "level": 0.19,
        "bugs": 0.2,
        "time": 178,
        "intelligentContent": 115.62,
        "number_operators": 35,
        "number_operands": 78,
        "number_operators_unique": 5,
        "number_operands_unique": 37,
        "cloc": 1,
        "loc": 142,
        "lloc": 133,
        "mi": 39.98,
        "mIwoC": 33.5,
        "commentWeight": 6.48,
        "kanDefect": 0.52,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 16,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 16,
        "package": "historial\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "matmanager\\Main",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "render",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 7,
        "loc": 94,
        "lloc": 82,
        "mi": 191.51,
        "mIwoC": 171,
        "commentWeight": 20.51,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "matmanager\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "login\\Login",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "login",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 6,
        "ccnMethodMax": 6,
        "externals": [
            "LoginUser\\Database"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 64,
        "vocabulary": 29,
        "volume": 310.91,
        "difficulty": 2.65,
        "effort": 825.11,
        "level": 0.38,
        "bugs": 0.1,
        "time": 46,
        "intelligentContent": 117.15,
        "number_operators": 18,
        "number_operands": 46,
        "number_operators_unique": 3,
        "number_operands_unique": 26,
        "cloc": 3,
        "loc": 44,
        "lloc": 41,
        "mi": 66.24,
        "mIwoC": 46.56,
        "commentWeight": 19.68,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 36,
        "totalStructuralComplexity": 72,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 72,
        "package": "login\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "materiales\\Main",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "render",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "templates\\header3",
            "LoginUser\\Database",
            "templates\\Footer"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 83,
        "vocabulary": 30,
        "volume": 407.27,
        "difficulty": 4.31,
        "effort": 1754.4,
        "level": 0.23,
        "bugs": 0.14,
        "time": 97,
        "intelligentContent": 94.55,
        "number_operators": 27,
        "number_operands": 56,
        "number_operators_unique": 4,
        "number_operands_unique": 26,
        "cloc": 0,
        "loc": 140,
        "lloc": 132,
        "mi": 35.06,
        "mIwoC": 35.06,
        "commentWeight": 0,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 16,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 16,
        "package": "materiales\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "materiales\\Materials",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "render",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 20,
        "ccn": 20,
        "ccnMethodMax": 20,
        "externals": [
            "LoginUser\\Database",
            "templates\\header2"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 236,
        "vocabulary": 75,
        "volume": 1470,
        "difficulty": 11.59,
        "effort": 17038.65,
        "level": 0.09,
        "bugs": 0.49,
        "time": 947,
        "intelligentContent": 126.82,
        "number_operators": 66,
        "number_operands": 170,
        "number_operators_unique": 9,
        "number_operands_unique": 66,
        "cloc": 6,
        "loc": 201,
        "lloc": 192,
        "mi": 38.55,
        "mIwoC": 25.32,
        "commentWeight": 13.22,
        "kanDefect": 1.08,
        "relativeStructuralComplexity": 81,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 81,
        "totalStructuralComplexity": 81,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 81,
        "package": "materiales\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "pedidos\\Order",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "render",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 11,
        "ccn": 11,
        "ccnMethodMax": 11,
        "externals": [
            "templates\\header3",
            "LoginUser\\Database",
            "LoginUser\\Database",
            "templates\\Footer"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 143,
        "vocabulary": 49,
        "volume": 802.9,
        "difficulty": 8.42,
        "effort": 6757.77,
        "level": 0.12,
        "bugs": 0.27,
        "time": 375,
        "intelligentContent": 95.39,
        "number_operators": 42,
        "number_operands": 101,
        "number_operators_unique": 7,
        "number_operands_unique": 42,
        "cloc": 4,
        "loc": 123,
        "lloc": 119,
        "mi": 46.69,
        "mIwoC": 32.91,
        "commentWeight": 13.79,
        "kanDefect": 0.66,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 25,
        "totalStructuralComplexity": 25,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 25,
        "package": "pedidos\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "RegisterProveedores\\MainProvider",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "render",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 16,
        "ccn": 16,
        "ccnMethodMax": 16,
        "externals": [
            "templates\\header",
            "LoginUser\\Database",
            "templates\\footer"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 188,
        "vocabulary": 59,
        "volume": 1105.94,
        "difficulty": 9.09,
        "effort": 10049.14,
        "level": 0.11,
        "bugs": 0.37,
        "time": 558,
        "intelligentContent": 121.71,
        "number_operators": 53,
        "number_operands": 135,
        "number_operators_unique": 7,
        "number_operands_unique": 52,
        "cloc": 9,
        "loc": 169,
        "lloc": 157,
        "mi": 46.13,
        "mIwoC": 28.63,
        "commentWeight": 17.5,
        "kanDefect": 0.85,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 9,
        "totalStructuralComplexity": 9,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 9,
        "package": "RegisterProveedores\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "tables\\MaterialsT",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "render",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "templates\\header2",
            "LoginUser\\Database",
            "templates\\Footer"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 120,
        "vocabulary": 47,
        "volume": 666.55,
        "difficulty": 4.14,
        "effort": 2759.21,
        "level": 0.24,
        "bugs": 0.22,
        "time": 153,
        "intelligentContent": 161.02,
        "number_operators": 31,
        "number_operands": 89,
        "number_operators_unique": 4,
        "number_operands_unique": 43,
        "cloc": 0,
        "loc": 145,
        "lloc": 137,
        "mi": 33.21,
        "mIwoC": 33.21,
        "commentWeight": 0,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 16,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 16,
        "package": "tables\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "tables\\Main",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "render",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "templates\\header",
            "LoginUser\\Database",
            "templates\\Footer"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 89,
        "vocabulary": 38,
        "volume": 467.07,
        "difficulty": 3.47,
        "effort": 1620.99,
        "level": 0.29,
        "bugs": 0.16,
        "time": 90,
        "intelligentContent": 134.58,
        "number_operators": 30,
        "number_operands": 59,
        "number_operators_unique": 4,
        "number_operands_unique": 34,
        "cloc": 1,
        "loc": 143,
        "lloc": 129,
        "mi": 41.32,
        "mIwoC": 34.87,
        "commentWeight": 6.46,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 16,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 16,
        "package": "tables\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "templates\\Footer",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "Footer",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 5,
        "vocabulary": 4,
        "volume": 10,
        "difficulty": 0,
        "effort": 0,
        "level": 1.6,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 16,
        "number_operators": 0,
        "number_operands": 5,
        "number_operators_unique": 0,
        "number_operands_unique": 4,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 73.16,
        "mIwoC": 73.16,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "templates\\",
        "pageRank": 0.07,
        "afferentCoupling": 6,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "templates\\header",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "head",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 5,
        "vocabulary": 4,
        "volume": 10,
        "difficulty": 0,
        "effort": 0,
        "level": 1.6,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 16,
        "number_operators": 0,
        "number_operands": 5,
        "number_operators_unique": 0,
        "number_operands_unique": 4,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 73.16,
        "mIwoC": 73.16,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "templates\\",
        "pageRank": 0.07,
        "afferentCoupling": 5,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "templates\\header2",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "head2",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 5,
        "vocabulary": 4,
        "volume": 10,
        "difficulty": 0,
        "effort": 0,
        "level": 1.6,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 16,
        "number_operators": 0,
        "number_operands": 5,
        "number_operators_unique": 0,
        "number_operands_unique": 4,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 73.16,
        "mIwoC": 73.16,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "templates\\",
        "pageRank": 0.05,
        "afferentCoupling": 3,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "templates\\header3",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "head3",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 5,
        "vocabulary": 4,
        "volume": 10,
        "difficulty": 0,
        "effort": 0,
        "level": 1.6,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 16,
        "number_operators": 0,
        "number_operands": 5,
        "number_operators_unique": 0,
        "number_operands_unique": 4,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 73.16,
        "mIwoC": 73.16,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "templates\\",
        "pageRank": 0.03,
        "afferentCoupling": 2,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "RegisterUser\\RegisterUserClass",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "RegisterUserF",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 19,
        "ccn": 19,
        "ccnMethodMax": 19,
        "externals": [
            "templates\\header",
            "templates\\Footer"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 221,
        "vocabulary": 64,
        "volume": 1326,
        "difficulty": 9.76,
        "effort": 12945.95,
        "level": 0.1,
        "bugs": 0.44,
        "time": 719,
        "intelligentContent": 135.82,
        "number_operators": 62,
        "number_operands": 159,
        "number_operators_unique": 7,
        "number_operands_unique": 57,
        "cloc": 10,
        "loc": 208,
        "lloc": 190,
        "mi": 42.53,
        "mIwoC": 25.87,
        "commentWeight": 16.66,
        "kanDefect": 0.92,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 4,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 4,
        "package": "RegisterUser\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    }
]