var classes = [
    {
        "name": "admin\\Main",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "render",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "templates\\header",
            "templates\\footer"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 14,
        "vocabulary": 6,
        "volume": 36.19,
        "difficulty": 1,
        "effort": 36.19,
        "level": 1,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 36.19,
        "number_operators": 4,
        "number_operands": 10,
        "number_operators_unique": 1,
        "number_operands_unique": 5,
        "cloc": 0,
        "loc": 96,
        "lloc": 91,
        "mi": 46.22,
        "mIwoC": 46.22,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 4,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 4,
        "package": "admin\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "bodeguero\\Main",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "render",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "templates\\header2",
            "matmanager\\Database"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 104,
        "vocabulary": 45,
        "volume": 571.15,
        "difficulty": 3.76,
        "effort": 2145.31,
        "level": 0.27,
        "bugs": 0.19,
        "time": 119,
        "intelligentContent": 152.06,
        "number_operators": 27,
        "number_operands": 77,
        "number_operators_unique": 4,
        "number_operands_unique": 41,
        "cloc": 0,
        "loc": 128,
        "lloc": 123,
        "mi": 34.7,
        "mIwoC": 34.7,
        "commentWeight": 0,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 9,
        "totalStructuralComplexity": 9,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 9,
        "package": "bodeguero\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "CRUD\\DeletePedidoClass",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "DeletePedidoF",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "matmanager\\Database"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 32,
        "vocabulary": 16,
        "volume": 128,
        "difficulty": 1.79,
        "effort": 228.57,
        "level": 0.56,
        "bugs": 0.04,
        "time": 13,
        "intelligentContent": 71.68,
        "number_operators": 7,
        "number_operands": 25,
        "number_operators_unique": 2,
        "number_operands_unique": 14,
        "cloc": 0,
        "loc": 30,
        "lloc": 29,
        "mi": 52.94,
        "mIwoC": 52.94,
        "commentWeight": 0,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 1,
        "package": "CRUD\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "CRUD\\DeleteProviderClass",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "DeleteProviderF",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "matmanager\\Database"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 32,
        "vocabulary": 16,
        "volume": 128,
        "difficulty": 1.79,
        "effort": 228.57,
        "level": 0.56,
        "bugs": 0.04,
        "time": 13,
        "intelligentContent": 71.68,
        "number_operators": 7,
        "number_operands": 25,
        "number_operators_unique": 2,
        "number_operands_unique": 14,
        "cloc": 0,
        "loc": 31,
        "lloc": 29,
        "mi": 52.94,
        "mIwoC": 52.94,
        "commentWeight": 0,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 1,
        "package": "CRUD\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "CRUD\\DeleteUserClass",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "DeleteUserF",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "matmanager\\Database"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 32,
        "vocabulary": 16,
        "volume": 128,
        "difficulty": 1.79,
        "effort": 228.57,
        "level": 0.56,
        "bugs": 0.04,
        "time": 13,
        "intelligentContent": 71.68,
        "number_operators": 7,
        "number_operands": 25,
        "number_operators_unique": 2,
        "number_operands_unique": 14,
        "cloc": 0,
        "loc": 30,
        "lloc": 29,
        "mi": 52.94,
        "mIwoC": 52.94,
        "commentWeight": 0,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 1,
        "package": "CRUD\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "CRUD\\EditMaterialClass",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "EditMaterialF",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "matmanager\\Database"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 41,
        "vocabulary": 21,
        "volume": 180.09,
        "difficulty": 1.79,
        "effort": 322.26,
        "level": 0.56,
        "bugs": 0.06,
        "time": 18,
        "intelligentContent": 100.64,
        "number_operators": 7,
        "number_operands": 34,
        "number_operators_unique": 2,
        "number_operands_unique": 19,
        "cloc": 0,
        "loc": 74,
        "lloc": 59,
        "mi": 45.31,
        "mIwoC": 45.31,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 36,
        "totalStructuralComplexity": 36,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 36,
        "package": "CRUD\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "CRUD\\EditProviderClass",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "EditProviderF",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "matmanager\\Database"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 40,
        "vocabulary": 20,
        "volume": 172.88,
        "difficulty": 1.83,
        "effort": 316.94,
        "level": 0.55,
        "bugs": 0.06,
        "time": 18,
        "intelligentContent": 94.3,
        "number_operators": 7,
        "number_operands": 33,
        "number_operators_unique": 2,
        "number_operands_unique": 18,
        "cloc": 1,
        "loc": 69,
        "lloc": 58,
        "mi": 54.87,
        "mIwoC": 45.59,
        "commentWeight": 9.27,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 36,
        "totalStructuralComplexity": 36,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 36,
        "package": "CRUD\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "CRUD\\EditPedidoClass",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "EditPedidoF",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "matmanager\\Database"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 36,
        "vocabulary": 17,
        "volume": 147.15,
        "difficulty": 1.93,
        "effort": 284.49,
        "level": 0.52,
        "bugs": 0.05,
        "time": 16,
        "intelligentContent": 76.11,
        "number_operators": 7,
        "number_operands": 29,
        "number_operators_unique": 2,
        "number_operands_unique": 15,
        "cloc": 1,
        "loc": 97,
        "lloc": 77,
        "mi": 51.23,
        "mIwoC": 43.4,
        "commentWeight": 7.83,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 36,
        "totalStructuralComplexity": 36,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 36,
        "package": "CRUD\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "CRUD\\EditUserClass",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "EditUserF",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "matmanager\\Database"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 68,
        "vocabulary": 30,
        "volume": 333.67,
        "difficulty": 3.06,
        "effort": 1019.54,
        "level": 0.33,
        "bugs": 0.11,
        "time": 57,
        "intelligentContent": 109.2,
        "number_operators": 13,
        "number_operands": 55,
        "number_operators_unique": 3,
        "number_operands_unique": 27,
        "cloc": 1,
        "loc": 153,
        "lloc": 142,
        "mi": 41.36,
        "mIwoC": 35.11,
        "commentWeight": 6.25,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 36,
        "totalStructuralComplexity": 36,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 36,
        "package": "CRUD\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "CRUD\\DeleteMaterialClass",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "DeleteMaterialF",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "matmanager\\Database"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 31,
        "vocabulary": 16,
        "volume": 124,
        "difficulty": 1.71,
        "effort": 212.57,
        "level": 0.58,
        "bugs": 0.04,
        "time": 12,
        "intelligentContent": 72.33,
        "number_operators": 7,
        "number_operands": 24,
        "number_operators_unique": 2,
        "number_operands_unique": 14,
        "cloc": 1,
        "loc": 32,
        "lloc": 28,
        "mi": 66.89,
        "mIwoC": 53.37,
        "commentWeight": 13.52,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 1,
        "package": "CRUD\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "CRUD\\UpdateMaterialClass",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "UpdateMaterialF",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "matmanager\\Database"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 47,
        "vocabulary": 16,
        "volume": 188,
        "difficulty": 1.23,
        "effort": 231.87,
        "level": 0.81,
        "bugs": 0.06,
        "time": 13,
        "intelligentContent": 152.43,
        "number_operators": 10,
        "number_operands": 37,
        "number_operators_unique": 1,
        "number_operands_unique": 15,
        "cloc": 0,
        "loc": 27,
        "lloc": 24,
        "mi": 53.83,
        "mIwoC": 53.83,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 16,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 16,
        "package": "CRUD\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "CRUD\\UpdatePedidoClass",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "UpdatePedidoF",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "matmanager\\Database"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 42,
        "vocabulary": 15,
        "volume": 164.09,
        "difficulty": 1.18,
        "effort": 193.39,
        "level": 0.85,
        "bugs": 0.05,
        "time": 11,
        "intelligentContent": 139.23,
        "number_operators": 9,
        "number_operands": 33,
        "number_operators_unique": 1,
        "number_operands_unique": 14,
        "cloc": 0,
        "loc": 26,
        "lloc": 23,
        "mi": 54.65,
        "mIwoC": 54.65,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 16,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 16,
        "package": "CRUD\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "CRUD\\UpdateProviderClass",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "UpdateProviderF",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "matmanager\\Database"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 48,
        "vocabulary": 16,
        "volume": 192,
        "difficulty": 1.27,
        "effort": 243.2,
        "level": 0.79,
        "bugs": 0.06,
        "time": 14,
        "intelligentContent": 151.58,
        "number_operators": 10,
        "number_operands": 38,
        "number_operators_unique": 1,
        "number_operands_unique": 15,
        "cloc": 1,
        "loc": 29,
        "lloc": 24,
        "mi": 67.96,
        "mIwoC": 53.77,
        "commentWeight": 14.19,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 16,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 16,
        "package": "CRUD\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "CRUD\\updateUserClass",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "updateUserF",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "matmanager\\Database"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 57,
        "vocabulary": 18,
        "volume": 237.69,
        "difficulty": 1.32,
        "effort": 314.58,
        "level": 0.76,
        "bugs": 0.08,
        "time": 17,
        "intelligentContent": 179.58,
        "number_operators": 12,
        "number_operands": 45,
        "number_operators_unique": 1,
        "number_operands_unique": 17,
        "cloc": 0,
        "loc": 29,
        "lloc": 26,
        "mi": 52.36,
        "mIwoC": 52.36,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 16,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 16,
        "package": "CRUD\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Database\\Database",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getConnection",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 17,
        "vocabulary": 12,
        "volume": 60.94,
        "difficulty": 3,
        "effort": 182.83,
        "level": 0.33,
        "bugs": 0.02,
        "time": 10,
        "intelligentContent": 20.31,
        "number_operators": 5,
        "number_operands": 12,
        "number_operators_unique": 4,
        "number_operands_unique": 8,
        "cloc": 0,
        "loc": 17,
        "lloc": 17,
        "mi": 60.39,
        "mIwoC": 60.39,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 2,
        "package": "Database\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "matmanager\\Database",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getConnection",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 17,
        "vocabulary": 12,
        "volume": 60.94,
        "difficulty": 3,
        "effort": 182.83,
        "level": 0.33,
        "bugs": 0.02,
        "time": 10,
        "intelligentContent": 20.31,
        "number_operators": 5,
        "number_operands": 12,
        "number_operators_unique": 4,
        "number_operands_unique": 8,
        "cloc": 1,
        "loc": 18,
        "lloc": 17,
        "mi": 78.25,
        "mIwoC": 60.39,
        "commentWeight": 17.85,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 2,
        "package": "matmanager\\",
        "pageRank": 0.49,
        "afferentCoupling": 28,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "gerente\\Main",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "render",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "templates\\header3",
            "templates\\Footer"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 14,
        "vocabulary": 5,
        "volume": 32.51,
        "difficulty": 1.25,
        "effort": 40.63,
        "level": 0.8,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 26.01,
        "number_operators": 4,
        "number_operands": 10,
        "number_operators_unique": 1,
        "number_operands_unique": 4,
        "cloc": 0,
        "loc": 41,
        "lloc": 35,
        "mi": 55.6,
        "mIwoC": 55.6,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 4,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 4,
        "package": "gerente\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "historial\\Main",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "render",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 5,
        "ccnMethodMax": 5,
        "externals": [
            "templates\\header",
            "matmanager\\Database",
            "templates\\Footer"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 113,
        "vocabulary": 42,
        "volume": 609.33,
        "difficulty": 5.27,
        "effort": 3211.34,
        "level": 0.19,
        "bugs": 0.2,
        "time": 178,
        "intelligentContent": 115.62,
        "number_operators": 35,
        "number_operands": 78,
        "number_operators_unique": 5,
        "number_operands_unique": 37,
        "cloc": 1,
        "loc": 142,
        "lloc": 133,
        "mi": 39.98,
        "mIwoC": 33.5,
        "commentWeight": 6.48,
        "kanDefect": 0.52,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 16,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 16,
        "package": "historial\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "matmanager\\Main",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "render",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 7,
        "loc": 94,
        "lloc": 82,
        "mi": 191.51,
        "mIwoC": 171,
        "commentWeight": 20.51,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "matmanager\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "login\\Login",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "login",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 6,
        "ccnMethodMax": 6,
        "externals": [
            "matmanager\\Database"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 69,
        "vocabulary": 32,
        "volume": 345,
        "difficulty": 3.71,
        "effort": 1281.43,
        "level": 0.27,
        "bugs": 0.12,
        "time": 71,
        "intelligentContent": 92.88,
        "number_operators": 17,
        "number_operands": 52,
        "number_operators_unique": 4,
        "number_operands_unique": 28,
        "cloc": 3,
        "loc": 52,
        "lloc": 49,
        "mi": 62.73,
        "mIwoC": 44.55,
        "commentWeight": 18.18,
        "kanDefect": 0.51,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 36,
        "totalStructuralComplexity": 72,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 72,
        "package": "login\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "materiales\\materiales",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "registerMateriales",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 13,
        "ccn": 13,
        "ccnMethodMax": 13,
        "externals": [
            "matmanager\\Database"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 136,
        "vocabulary": 47,
        "volume": 755.42,
        "difficulty": 7.96,
        "effort": 6015.06,
        "level": 0.13,
        "bugs": 0.25,
        "time": 334,
        "intelligentContent": 94.87,
        "number_operators": 45,
        "number_operands": 91,
        "number_operators_unique": 7,
        "number_operands_unique": 40,
        "cloc": 6,
        "loc": 63,
        "lloc": 57,
        "mi": 62.8,
        "mIwoC": 39.8,
        "commentWeight": 23,
        "kanDefect": 0.57,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.71,
        "relativeSystemComplexity": 36.71,
        "totalStructuralComplexity": 36,
        "totalDataComplexity": 0.71,
        "totalSystemComplexity": 36.71,
        "package": "materiales\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "materiales\\Main",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "render",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "templates\\header2",
            "matmanager\\Database",
            "templates\\Footer"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 83,
        "vocabulary": 30,
        "volume": 407.27,
        "difficulty": 4.31,
        "effort": 1754.4,
        "level": 0.23,
        "bugs": 0.14,
        "time": 97,
        "intelligentContent": 94.55,
        "number_operators": 27,
        "number_operands": 56,
        "number_operators_unique": 4,
        "number_operands_unique": 26,
        "cloc": 0,
        "loc": 140,
        "lloc": 132,
        "mi": 35.06,
        "mIwoC": 35.06,
        "commentWeight": 0,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 16,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 16,
        "package": "materiales\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "materiales\\Materials",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "render",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 8,
        "ccn": 8,
        "ccnMethodMax": 8,
        "externals": [
            "matmanager\\Database",
            "templates\\header2"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 94,
        "vocabulary": 42,
        "volume": 506.88,
        "difficulty": 6.9,
        "effort": 3497.46,
        "level": 0.14,
        "bugs": 0.17,
        "time": 194,
        "intelligentContent": 73.46,
        "number_operators": 25,
        "number_operands": 69,
        "number_operators_unique": 7,
        "number_operands_unique": 35,
        "cloc": 0,
        "loc": 142,
        "lloc": 139,
        "mi": 33.24,
        "mIwoC": 33.24,
        "commentWeight": 0,
        "kanDefect": 0.66,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 64,
        "totalStructuralComplexity": 64,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 64,
        "package": "materiales\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "materiales\\registerMateriales",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "registerMateriales",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 13,
        "ccn": 13,
        "ccnMethodMax": 13,
        "externals": [
            "matmanager\\Database"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 136,
        "vocabulary": 47,
        "volume": 755.42,
        "difficulty": 7.96,
        "effort": 6015.06,
        "level": 0.13,
        "bugs": 0.25,
        "time": 334,
        "intelligentContent": 94.87,
        "number_operators": 45,
        "number_operands": 91,
        "number_operators_unique": 7,
        "number_operands_unique": 40,
        "cloc": 6,
        "loc": 63,
        "lloc": 57,
        "mi": 62.8,
        "mIwoC": 39.8,
        "commentWeight": 23,
        "kanDefect": 0.57,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.71,
        "relativeSystemComplexity": 36.71,
        "totalStructuralComplexity": 36,
        "totalDataComplexity": 0.71,
        "totalSystemComplexity": 36.71,
        "package": "materiales\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "pedidos\\pedidos",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "RegisterPedido",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 10,
        "ccn": 10,
        "ccnMethodMax": 10,
        "externals": [
            "matmanager\\Database"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 91,
        "vocabulary": 30,
        "volume": 446.53,
        "difficulty": 6.3,
        "effort": 2813.12,
        "level": 0.16,
        "bugs": 0.15,
        "time": 156,
        "intelligentContent": 70.88,
        "number_operators": 28,
        "number_operands": 63,
        "number_operators_unique": 5,
        "number_operands_unique": 25,
        "cloc": 0,
        "loc": 33,
        "lloc": 33,
        "mi": 46.98,
        "mIwoC": 46.98,
        "commentWeight": 0,
        "kanDefect": 0.43,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.67,
        "relativeSystemComplexity": 4.67,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 0.67,
        "totalSystemComplexity": 4.67,
        "package": "pedidos\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "pedidos\\Order",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "render",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "templates\\header3",
            "matmanager\\Database",
            "templates\\Footer"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 46,
        "vocabulary": 22,
        "volume": 205.13,
        "difficulty": 4.41,
        "effort": 905,
        "level": 0.23,
        "bugs": 0.07,
        "time": 50,
        "intelligentContent": 46.5,
        "number_operators": 16,
        "number_operands": 30,
        "number_operators_unique": 5,
        "number_operands_unique": 17,
        "cloc": 3,
        "loc": 97,
        "lloc": 94,
        "mi": 53.82,
        "mIwoC": 40.37,
        "commentWeight": 13.45,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 25,
        "totalStructuralComplexity": 25,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 25,
        "package": "pedidos\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "pedidos\\RegistrarPedido",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "RegisterPedido",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 9,
        "ccn": 9,
        "ccnMethodMax": 9,
        "externals": [
            "matmanager\\Database"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 97,
        "vocabulary": 32,
        "volume": 485,
        "difficulty": 5.07,
        "effort": 2459.64,
        "level": 0.2,
        "bugs": 0.16,
        "time": 137,
        "intelligentContent": 95.63,
        "number_operators": 26,
        "number_operands": 71,
        "number_operators_unique": 4,
        "number_operands_unique": 28,
        "cloc": 1,
        "loc": 31,
        "lloc": 30,
        "mi": 61.5,
        "mIwoC": 47.76,
        "commentWeight": 13.73,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 1,
        "package": "pedidos\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "proveedores\\Proveedores",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "RegisterProvider",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 15,
        "ccn": 15,
        "ccnMethodMax": 15,
        "externals": [
            "matmanager\\Database"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 147,
        "vocabulary": 46,
        "volume": 811.96,
        "difficulty": 8.71,
        "effort": 7068.25,
        "level": 0.11,
        "bugs": 0.27,
        "time": 393,
        "intelligentContent": 93.27,
        "number_operators": 50,
        "number_operands": 97,
        "number_operators_unique": 7,
        "number_operands_unique": 39,
        "cloc": 9,
        "loc": 64,
        "lloc": 55,
        "mi": 67.09,
        "mIwoC": 39.65,
        "commentWeight": 27.44,
        "kanDefect": 0.78,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 4.5,
        "relativeSystemComplexity": 5.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 4.5,
        "totalSystemComplexity": 5.5,
        "package": "proveedores\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "RegisterProveedores\\MainProvider",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "render",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "templates\\header",
            "templates\\footer"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 14,
        "vocabulary": 5,
        "volume": 32.51,
        "difficulty": 1.25,
        "effort": 40.63,
        "level": 0.8,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 26.01,
        "number_operators": 4,
        "number_operands": 10,
        "number_operators_unique": 1,
        "number_operands_unique": 4,
        "cloc": 0,
        "loc": 96,
        "lloc": 90,
        "mi": 46.65,
        "mIwoC": 46.65,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 4,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 4,
        "package": "RegisterProveedores\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "RegisterProveedores\\RegisterProveedores",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "RegisterProvider",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 15,
        "ccn": 15,
        "ccnMethodMax": 15,
        "externals": [
            "matmanager\\Database"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 156,
        "vocabulary": 54,
        "volume": 897.76,
        "difficulty": 8.12,
        "effort": 7287.16,
        "level": 0.12,
        "bugs": 0.3,
        "time": 405,
        "intelligentContent": 110.6,
        "number_operators": 47,
        "number_operands": 109,
        "number_operators_unique": 7,
        "number_operands_unique": 47,
        "cloc": 9,
        "loc": 76,
        "lloc": 67,
        "mi": 62.88,
        "mIwoC": 37.47,
        "commentWeight": 25.41,
        "kanDefect": 0.78,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 3,
        "relativeSystemComplexity": 4,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 4,
        "package": "RegisterProveedores\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "tables\\MaterialsT",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "render",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "templates\\header2",
            "matmanager\\Database",
            "templates\\Footer"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 120,
        "vocabulary": 48,
        "volume": 670.2,
        "difficulty": 4.05,
        "effort": 2711.25,
        "level": 0.25,
        "bugs": 0.22,
        "time": 151,
        "intelligentContent": 165.67,
        "number_operators": 31,
        "number_operands": 89,
        "number_operators_unique": 4,
        "number_operands_unique": 44,
        "cloc": 1,
        "loc": 169,
        "lloc": 157,
        "mi": 37.85,
        "mIwoC": 31.91,
        "commentWeight": 5.94,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 16,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 16,
        "package": "tables\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "tables\\Main",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "render",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "templates\\header",
            "matmanager\\Database",
            "templates\\Footer"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 89,
        "vocabulary": 38,
        "volume": 467.07,
        "difficulty": 3.47,
        "effort": 1620.99,
        "level": 0.29,
        "bugs": 0.16,
        "time": 90,
        "intelligentContent": 134.58,
        "number_operators": 30,
        "number_operands": 59,
        "number_operators_unique": 4,
        "number_operands_unique": 34,
        "cloc": 1,
        "loc": 143,
        "lloc": 129,
        "mi": 41.32,
        "mIwoC": 34.87,
        "commentWeight": 6.46,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 16,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 16,
        "package": "tables\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "templates\\Footer",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "Footer",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 5,
        "vocabulary": 4,
        "volume": 10,
        "difficulty": 0,
        "effort": 0,
        "level": 1.6,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 16,
        "number_operators": 0,
        "number_operands": 5,
        "number_operators_unique": 0,
        "number_operands_unique": 4,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 73.16,
        "mIwoC": 73.16,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "templates\\",
        "pageRank": 0.06,
        "afferentCoupling": 7,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "templates\\header",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "head",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 5,
        "vocabulary": 4,
        "volume": 10,
        "difficulty": 0,
        "effort": 0,
        "level": 1.6,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 16,
        "number_operators": 0,
        "number_operands": 5,
        "number_operators_unique": 0,
        "number_operands_unique": 4,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 73.16,
        "mIwoC": 73.16,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "templates\\",
        "pageRank": 0.04,
        "afferentCoupling": 4,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "templates\\header2",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "head2",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 5,
        "vocabulary": 4,
        "volume": 10,
        "difficulty": 0,
        "effort": 0,
        "level": 1.6,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 16,
        "number_operators": 0,
        "number_operands": 5,
        "number_operators_unique": 0,
        "number_operands_unique": 4,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 73.16,
        "mIwoC": 73.16,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "templates\\",
        "pageRank": 0.04,
        "afferentCoupling": 4,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "templates\\header3",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "head3",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 5,
        "vocabulary": 4,
        "volume": 10,
        "difficulty": 0,
        "effort": 0,
        "level": 1.6,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 16,
        "number_operators": 0,
        "number_operands": 5,
        "number_operators_unique": 0,
        "number_operands_unique": 4,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 73.16,
        "mIwoC": 73.16,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "templates\\",
        "pageRank": 0.03,
        "afferentCoupling": 2,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "users\\Users",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "processRegistration",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 14,
        "ccn": 14,
        "ccnMethodMax": 14,
        "externals": [
            "matmanager\\Database"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 143,
        "vocabulary": 41,
        "volume": 766.13,
        "difficulty": 9.99,
        "effort": 7650.03,
        "level": 0.1,
        "bugs": 0.26,
        "time": 425,
        "intelligentContent": 76.73,
        "number_operators": 46,
        "number_operands": 97,
        "number_operators_unique": 7,
        "number_operands_unique": 34,
        "cloc": 7,
        "loc": 53,
        "lloc": 46,
        "mi": 68.34,
        "mIwoC": 41.65,
        "commentWeight": 26.69,
        "kanDefect": 0.57,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 3,
        "relativeSystemComplexity": 4,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 4,
        "package": "users\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "users\\UsersForm",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "renderRegisterForm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "templates\\Header",
            "templates\\Footer"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 11,
        "vocabulary": 5,
        "volume": 25.54,
        "difficulty": 1,
        "effort": 25.54,
        "level": 1,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 25.54,
        "number_operators": 3,
        "number_operands": 8,
        "number_operators_unique": 1,
        "number_operands_unique": 4,
        "cloc": 0,
        "loc": 135,
        "lloc": 128,
        "mi": 44.05,
        "mIwoC": 44.05,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 4,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 4,
        "package": "users\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "users\\users",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "processRegistration",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 14,
        "ccn": 14,
        "ccnMethodMax": 14,
        "externals": [
            "matmanager\\Database"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 143,
        "vocabulary": 41,
        "volume": 766.13,
        "difficulty": 9.99,
        "effort": 7650.03,
        "level": 0.1,
        "bugs": 0.26,
        "time": 425,
        "intelligentContent": 76.73,
        "number_operators": 46,
        "number_operands": 97,
        "number_operators_unique": 7,
        "number_operands_unique": 34,
        "cloc": 7,
        "loc": 53,
        "lloc": 46,
        "mi": 68.34,
        "mIwoC": 41.65,
        "commentWeight": 26.69,
        "kanDefect": 0.57,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 3,
        "relativeSystemComplexity": 4,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 4,
        "package": "users\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    }
]